version: '3.4'

services:
  gulag-front:
      image: gitlab.urbica.co:5001/gulag/gulagmap:dev
      container_name: gulag-front
      restart: always
      environment:
        - VIRTUAL_HOST=gulag-next.urbica.co
        - LETSENCRYPT_HOST=gulag-next.urbica.co
        - LETSENCRYPT_EMAIL=hello@urbica.co
#      ports:
#        - 4000:80
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - gulag-api

  gulag-api:
    image: gitlab.urbica.co:5001/device25/gulag-workshop:master
    container_name: gulag-api
    restart: always
    env_file:
      - .env
#    volumes:
#      - ./uploads:/usr/src/app/uploads
    depends_on:
      - gulag-db

  gulag-db:
      image: mdillon/postgis:9.6-alpine
      container_name: gulag-db
      restart: always
      environment:
        - POSTGRES_DB=db
      volumes:
        - ./db:/var/lib/postgresql/data

networks:
  default:
    external:
      name: production-network
