version: '3.6'

services:
  traefik:
    image: traefik:1.5.4-alpine
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik:/etc/traefik:Z
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    command:
      - --logLevel=DEBUG
      - --entrypoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::443 TLS
      - --defaultentrypoints=http,https
      - --acme
      - --acme.email=hello@urbica.co
      - --acme.storage=/etc/traefik/acme.json
      - --acme.entryPoint=https
      - --acme.httpChallenge.entryPoint=http
      - --acme.OnHostRule=true
      - --acme.onDemand=false
      - --acme.acmeLogging=true
      - --web
      - --docker
      - --docker.watch
      - --docker.exposedbydefault=false
      - --docker.domain=gulagmap.ru

  gulag-front:
    image: gitlab.urbica.co:5001/gulag/front:master
    container_name: gulag-front
    restart: always
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:gulagmap.ru
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
    external: false